name: "farm1" #name of farm
environments: #environments are a list of dictionaries
- name: "env1"  #name of environment
  beds: #beds are a list of dictionaries for each environment
    - name: "bed1"  #name of bed
      plants: #plants are a list of dictionaries for each bed
        - name: "lettuce1" #name of plant
      sensors:
        - type: "air"
          name: "air1"
        - type: "reservoir"
          name: "reservoir1"
        - type: "camera"
          name: "camera1"
        - type: "light"
          name: "light1"
      actuators:
        - type: "Artificial EC"
        - type: "Artificial pH"
- name: "env2"
  beds:
    - name: "bed2"
      plants:
        - name: "lettuce1"
    - name: "bed3"  
      plants:
        - name: "tomato1"
  sensors:
  - type: "Artificial Temp"
    refresh: 5
    value: 16
connection:
  host: "influxdb"
  port: 8086
  username: "grafana"
  password: "password"
  database: "grafana"

